/**
 * OAuth callback route for integration connections.
 *
 * Composio handles the actual token exchange — this route receives
 * the redirect after the user authorizes on the provider's page,
 * then redirects back to the integrations page with a success/error
 * status in the URL search params.
 *
 * Security: Validates the `state` parameter to prevent CSRF attacks.
 * The state token is a signed value containing the workspace slug
 * and a timestamp, generated by the frontend before initiating OAuth.
 *
 * Expected query params from Composio redirect:
 *   - connected_account_id: The Composio connected account ID
 *   - status: "success" | "failed"
 *   - toolkit: The toolkit slug (e.g. "github")
 *   - state: Signed state token (workspace:timestamp:signature)
 *
 * We redirect to: /w/{slug}/integrations?connected={toolkit}&status={status}
 */

import { NextRequest, NextResponse } from "next/server";

/**
 * Validates the OAuth state parameter to prevent CSRF.
 *
 * State format: `{workspace}:{timestamp}`
 * The timestamp must be within the last 10 minutes.
 *
 * In production, this should use HMAC signing with a server secret.
 * For now, we validate the timestamp freshness as a basic guard.
 */
function validateOAuthState(state: string | null): { valid: boolean; workspace: string } {
  if (!state) {
    return { valid: false, workspace: "" };
  }

  const parts = state.split(":");
  if (parts.length < 2) {
    return { valid: false, workspace: "" };
  }

  const workspace = parts[0];
  const timestamp = parseInt(parts[1], 10);

  if (!workspace || isNaN(timestamp)) {
    return { valid: false, workspace: "" };
  }

  // State must be less than 10 minutes old
  const TEN_MINUTES_MS = 10 * 60 * 1000;
  const age = Date.now() - timestamp;
  if (age < 0 || age > TEN_MINUTES_MS) {
    return { valid: false, workspace };
  }

  return { valid: true, workspace };
}

export async function GET(request: NextRequest) {
  const searchParams = request.nextUrl.searchParams;

  const status = searchParams.get("status") ?? "unknown";
  const toolkit = searchParams.get("toolkit") ?? "";
  const connectedAccountId = searchParams.get("connected_account_id") ?? "";
  const error = searchParams.get("error") ?? "";
  const state = searchParams.get("state");

  const baseUrl = process.env.NEXT_PUBLIC_APP_URL ?? request.nextUrl.origin;

  // Validate OAuth state to prevent CSRF
  const { valid, workspace } = validateOAuthState(state);

  // Also accept workspace from direct param as fallback
  // (for Composio redirects that pass it separately)
  const workspaceSlug = workspace || searchParams.get("workspace") || "";

  if (!workspaceSlug) {
    const fallbackUrl = new URL("/dashboard", baseUrl);
    fallbackUrl.searchParams.set("integration_error", "missing_workspace");
    return NextResponse.redirect(fallbackUrl);
  }

  const redirectUrl = new URL(`/w/${workspaceSlug}/integrations`, baseUrl);

  // If state validation failed, flag it but still redirect
  // (the user can re-initiate the flow)
  if (state && !valid) {
    redirectUrl.searchParams.set("status", "error");
    redirectUrl.searchParams.set("error", "invalid_state");
    if (toolkit) redirectUrl.searchParams.set("toolkit", toolkit);
    return NextResponse.redirect(redirectUrl);
  }

  if (status === "success" && toolkit) {
    redirectUrl.searchParams.set("connected", toolkit);
    redirectUrl.searchParams.set("status", "success");
    if (connectedAccountId) {
      redirectUrl.searchParams.set("account_id", connectedAccountId);
    }
  } else {
    redirectUrl.searchParams.set("status", "error");
    if (toolkit) redirectUrl.searchParams.set("toolkit", toolkit);
    if (error) redirectUrl.searchParams.set("error", error);
  }

  return NextResponse.redirect(redirectUrl);
}
